CATALOGUE_HOST: catalogue.backend-{{ env }}.kranthicart.fun
USER_HOST: user.backend-{{ env }}.kranthicart.fun
CART_HOST: cart.backend-{{ env }}.kranthicart.fun
SHIPPING_HOST: shipping.backend-{{ env }}.kranthicart.fun
PAYMENT_HOST: payment.backend-{{ env }}.kranthicart.fun