CART_HOST: cart.backend-{{ env }}.kranthicart.fun
USER_HOST: user.backend-{{ env }}.kranthicart.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.kranthicart.fun
RABBITMQ_USER: roboshop
RABBITMQ_PASSWORD: roboshop123